Initial work to address the loss of data when combining usage items.
alan-turing-institute/rctab-functions pull request #43
Opened 2024-09-23 13:20 UTC by dlpbc

Initial work to address #42

2025-03-18 12:54 UTC, Iain-S requested changes

2025-03-21 16:40 UTC, dlpbc commented
Latest commit about the addition of a new retrieve usage test (i.e., `test_retrieve_usage_3`) should fail as expected. The `retrieve_usage` function which it uses implements the incorrect process of combining usage items. We would need to swap `combine_items` with `combine_itemz` in `utils/usage.py`.

2025-03-21 16:50 UTC, dlpbc commented
`test_retrieve_usage_3` now passes with the latest commit.

2025-03-21 16:53 UTC, dlpbc commented
TODO:
- [ ] Come up with a proper name for the `combine_itemz` function.

2025-04-02 09:31 UTC, Iain-S commented
- [ ] Iain: Check whether cost should always equal quantity * price or quantity * effective_price or some other invariant should hold or none at all.

2025-04-02 09:42 UTC, dlpbc commented
> TODO:
> 
>     * [x]  Come up with a proper name for the `combine_itemz` function.

Name suggestion: `compress_items`
- [ ] Ese: Rename the function and update the affected scripts.

2025-04-15 23:11 UTC, dlpbc commented
> > TODO:
> > ```
> > * [x]  Come up with a proper name for the `combine_itemz` function.
> > ```
> 
> Name suggestion: `compress_items`
> 
>     * [x]  Ese: Rename the function and update the affected scripts.

Done. However, docker builds are now failing across all apps during Github actions check.

2025-05-16 14:20 UTC, Iain-S approved these changes
Good to go!

2025-05-16 14:20 UTC, merged